theme: jekyll-theme-minimal
title: Makayla Moster
description: CS Ph.D. student at Clemson University | <a href="http://clemsonhfse.com/index.html" target="_blank">Human Factors Software Engineering (HFSE) Team</a>
logo: assets/images/IMG_1715.png
google_analytics: UA-165249753-1
