theme: jekyll-theme-minimal
title: Makayla Moster
description: CS Ph.D. student at Clemson University <br/> <a href="http://clemsonhfse.com/index.html" target="_blank">Human Factors Software Engineering</a> <br/> Pronouns - she/her/hers
logo: assets/images/IMG_1715.png
google_analytics: UA-165249753-1
