# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Makayla Moster
tagline:          'CS Ph.D. Student'
description:      'CS Ph.D. Student <br/> Clemson University'
url:              https://makayla-moster.github.io
baseurl:          https://makayla-moster.github.io
logo:             /assets/images/IMG_1715.png
